/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2021-03-09 08:47:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.layout;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/layout/../layout/footer.jsp", Long.valueOf(1615278891245L));
    _jspx_dependants.put("/layout/../layout/header.jsp", Long.valueOf(1615279600525L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>java.gg</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("/* 헤더 배경색 : 5383E8, 배치  */\r\n");
      out.write(".navbar {\r\n");
      out.write("\tbackground-color: #5383E8;\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tjustify-content: space-between;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header-ul {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 헤더 글자 하얀색 */\r\n");
      out.write(".nav-link {\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 헤더 메뉴 센터 맞추기 */\r\n");
      out.write(".nav-item {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tjustify-content: center;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("\tmargin-left: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-brand {\r\n");
      out.write("\tmargin-left: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-btn {\r\n");
      out.write("\tmargin-right: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 헤더 검색 다자인 */\r\n");
      out.write(".btn_image {\r\n");
      out.write("\tbackground-image: url(\"../assets/img/searchImage.svg\");\r\n");
      out.write("\tbackground-size: cover;\r\n");
      out.write("\theight: 33px;\r\n");
      out.write("\twidth: 75px;\r\n");
      out.write("\tborder: 0;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\tmargin-right: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-control {\r\n");
      out.write("\theight: 33px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header-btn {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-sm\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"header-ul\">\r\n");
      out.write("\r\n");
      out.write("  <a class=\"navbar-brand\" href=\"#\">\r\n");
      out.write("    <img src=\"../assets/img/logo.svg\" alt=\"logo\" style=\"width:40px;\">\r\n");
      out.write("  </a>\r\n");
      out.write("  \r\n");
      out.write("  <ul class=\"navbar-nav\">\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"#\">#집에 있자</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"#\">통계</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"#\">랭킹</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"#\">커뮤니티</a>\r\n");
      out.write("    </li>\r\n");
      out.write("  </ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"header-btn\">\r\n");
      out.write("  <form class=\"form-inline\" action=\"/action_page.php\">\r\n");
      out.write("    <input class=\"form-control\" type=\"text\" placeholder=\"소환사명, 소환사명, ...\">\r\n");
      out.write("    <button type=\"button\" class=\"btn_image\" id=\"img_btn\"></button>\r\n");
      out.write("  </form>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"login-btn\">\r\n");
      out.write("  \t<button type=\"button\" class=\"btn btn-primary btn-md\" style=\"background-color: #232F46\">로그인</button>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/home_style.css\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color: #5383E8\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- 컨테이너 -->\r\n");
      out.write("\t<div id=\"home_container\" align=\"center\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 로고 -->\r\n");
      out.write("\t\t<div id=\"home_logo\">\r\n");
      out.write("\t\t\t<img style=\"height: 200px\" src=\"../assets/img/mainpic.png\" /> <br />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<br />\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 검색창 -->\r\n");
      out.write("\t\t<div id=\"home_input\">\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"searchUser\" id=\"searchUser\"\r\n");
      out.write("\t\t\t\tplaceholder=\"소환사명, 소환사명,...\"\r\n");
      out.write("\t\t\t\tstyle=\"width: 600px; height: 40px; border-radius: 5px; padding: 5px 0 5px 15px;\">\r\n");
      out.write("\t\t\t<button id=\"home_search_button\"><b>.GG</b></button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<br /> <br /> <br />\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 인기글 -->\r\n");
      out.write("\t\t<div id=\"home_hot_post_container\">\r\n");
      out.write("\t\t\t<div align=\"left\"\r\n");
      out.write("\t\t\t\tstyle=\"height: 30px; margin: 5px; display: flex; justify-content: left; align-items: center; font-size: 10px; font-style: bold; margin-left: 13px;\">\r\n");
      out.write("\t\t\t\t<b>OP.GGTalk 인기글</b></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 인기글 1층 -->\r\n");
      out.write("\t\t\t<div style=\"display: flex;\">\r\n");
      out.write("\t\t\t\t<!-- 인기글 블럭 하나 -->\r\n");
      out.write("\t\t\t\t<div id=\"post_box\"\r\n");
      out.write("\t\t\t\t\tstyle=\"display: flex; border-top: 0.5px solid #F0F0F0; border-right: 0.5px solid #F0F0F0; border-bottom: 0.5px solid #F0F0F0; width: 50%;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div id=\"post_rank\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 50px; display: flex; justify-content: center; align-items: center; color: #1AB80C;\">1</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"post_pic\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"../assets/img/pic1.png\" style=\"width: 40px;\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div style=\"margin-left: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t<div style=\"display: flex; margin-bottom: 3px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"post_title\">한지민</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"post_comment_count\">[55]</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"display: flex; margin-top: 3px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"post_timestamp\">8시간 전</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"username\">한지민 fan</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- 인기글 블럭 끝 -->\r\n");
      out.write("\t\t\t\t<div id=\"post_box\"\r\n");
      out.write("\t\t\t\t\tstyle=\"display: flex; border-top: 0.5px solid #F0F0F0; border-bottom: 0.5px solid #F0F0F0; width: 50%;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div id=\"post_rank\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 50px; display: flex; justify-content: center; align-items: center; color: #1AB80C;\">2</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"post_pic\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"../assets/img/pic1.png\" style=\"width: 40px;\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div style=\"margin-left: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t<div style=\"display: flex; margin-bottom: 3px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"post_title\">한지민</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"post_comment_count\">[55]</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"display: flex; margin-top: 3px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"post_timestamp\">8시간 전</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"username\">한지민 fan</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 인기글 1층 끝 -->\r\n");
      out.write("\t\t\t<!-- 2층 -->\r\n");
      out.write("\t\t\t<div style=\"display: flex;\">\r\n");
      out.write("\t\t\t\t<!-- 인기글 블럭 하나 -->\r\n");
      out.write("\t\t\t\t<div id=\"post_box\"\r\n");
      out.write("\t\t\t\t\tstyle=\"display: flex; border-right: 0.5px solid #F0F0F0; border-bottom: 0.5px solid #F0F0F0; width: 50%;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div id=\"post_rank\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 50px; display: flex; justify-content: center; align-items: center; color: #1AB80C;\">3</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"post_pic\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"../assets/img/pic1.png\" style=\"width: 40px;\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div style=\"margin-left: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t<div style=\"display: flex; margin-bottom: 3px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"post_title\">한지민</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"post_comment_count\">[55]</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"display: flex; margin-top: 3px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"post_timestamp\">8시간 전</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"username\">한지민 fan</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- 인기글 블럭 끝 -->\r\n");
      out.write("\t\t\t\t<div id=\"post_box\"\r\n");
      out.write("\t\t\t\t\tstyle=\"display: flex; border-bottom: 0.5px solid #F0F0F0; width: 50%;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div id=\"post_rank\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 50px; display: flex; justify-content: center; align-items: center; color: #1AB80C;\">4</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"post_pic\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"../assets/img/pic1.png\" style=\"width: 40px;\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div style=\"margin-left: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t<div style=\"display: flex; margin-bottom: 3px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"post_title\">한지민</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"post_comment_count\">[55]</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"display: flex; margin-top: 3px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"post_timestamp\">8시간 전</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"username\">한지민 fan</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 2층 끝 -->\r\n");
      out.write("\t\t\t<!-- 3층 -->\r\n");
      out.write("\t\t\t<div style=\"display: flex;\">\r\n");
      out.write("\t\t\t\t<!-- 인기글 블럭 하나 -->\r\n");
      out.write("\t\t\t\t<div id=\"post_box\"\r\n");
      out.write("\t\t\t\t\tstyle=\"display: flex; border-right: 0.5px solid #F0F0F0; border-bottom: 0.5px solid #F0F0F0; width: 50%;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div id=\"post_rank\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 50px; display: flex; justify-content: center; align-items: center; color: #1AB80C;\">5</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"post_pic\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"../assets/img/pic1.png\" style=\"width: 40px;\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div style=\"margin-left: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t<div style=\"display: flex; margin-bottom: 3px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"post_title\">한지민</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"post_comment_count\">[55]</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"display: flex; margin-top: 3px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"post_timestamp\">8시간 전</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"username\">한지민 fan</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- 인기글 블럭 끝 -->\r\n");
      out.write("\t\t\t\t<div id=\"post_box\"\r\n");
      out.write("\t\t\t\t\tstyle=\"display: flex; border-bottom: 0.5px solid #F0F0F0; width: 50%;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div id=\"post_rank\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 50px; display: flex; justify-content: center; align-items: center; color: #1AB80C;\">6</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"post_pic\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"../assets/img/pic1.png\" style=\"width: 40px;\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div style=\"margin-left: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t<div style=\"display: flex; margin-bottom: 3px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"post_title\">한지민</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"post_comment_count\">[55]</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"display: flex; margin-top: 3px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"post_timestamp\">8시간 전</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"username\">한지민 fan</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 3층 끝 -->\r\n");
      out.write("\t\t\t<!-- 4층 -->\r\n");
      out.write("\t\t\t<div style=\"display: flex;\">\r\n");
      out.write("\t\t\t\t<!-- 인기글 블럭 하나 -->\r\n");
      out.write("\t\t\t\t<div id=\"post_box\"\r\n");
      out.write("\t\t\t\t\tstyle=\"display: flex; border-right: 0.5px solid #F0F0F0; border-bottom: 0.5px solid #F0F0F0; width: 50%;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div id=\"post_rank\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 50px; display: flex; justify-content: center; align-items: center; color: #1AB80C;\">7</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"post_pic\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"../assets/img/pic1.png\" style=\"width: 40px;\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div style=\"margin-left: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t<div style=\"display: flex; margin-bottom: 3px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"post_title\">한지민</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"post_comment_count\">[55]</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"display: flex; margin-top: 3px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"post_timestamp\">8시간 전</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"username\">한지민 fan</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- 인기글 블럭 끝 -->\r\n");
      out.write("\t\t\t\t<div id=\"post_box\"\r\n");
      out.write("\t\t\t\t\tstyle=\"display: flex; border-bottom: 0.5px solid #F0F0F0; width: 50%;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div id=\"post_rank\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 50px; display: flex; justify-content: center; align-items: center; color: #1AB80C;\">8</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"post_pic\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"../assets/img/pic1.png\" style=\"width: 40px;\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div style=\"margin-left: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t<div style=\"display: flex; margin-bottom: 3px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"post_title\">한지민</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"post_comment_count\">[55]</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"display: flex; margin-top: 3px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"post_timestamp\">8시간 전</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"username\">한지민 fan</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 4층 끝 -->\r\n");
      out.write("\t\t\t<!-- 5층 -->\r\n");
      out.write("\t\t\t<div style=\"display: flex;\">\r\n");
      out.write("\t\t\t\t<!-- 인기글 블럭 하나 -->\r\n");
      out.write("\t\t\t\t<div id=\"post_box\"\r\n");
      out.write("\t\t\t\t\tstyle=\"display: flex; border-right: 0.5px solid #F0F0F0; border-bottom: 0.5px solid #F0F0F0; width: 50%;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div id=\"post_rank\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 50px; display: flex; justify-content: center; align-items: center; color: #1AB80C;\">9</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"post_pic\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"../assets/img/pic1.png\" style=\"width: 40px;\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div style=\"margin-left: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t<div style=\"display: flex; margin-bottom: 3px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"post_title\">한지민</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"post_comment_count\">[55]</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"display: flex; margin-top: 3px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"post_timestamp\">8시간 전</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"username\">한지민 fan</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- 인기글 블럭 끝 -->\r\n");
      out.write("\t\t\t\t<div id=\"post_box\"\r\n");
      out.write("\t\t\t\t\tstyle=\"display: flex; border-bottom: 0.5px solid #F0F0F0; width: 50%;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div id=\"post_rank\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 50px; display: flex; justify-content: center; align-items: center; color: #1AB80C;\">10</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"post_pic\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"../assets/img/pic1.png\" style=\"width: 40px;\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div style=\"margin-left: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t<div style=\"display: flex; margin-bottom: 3px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"post_title\">한지민</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"post_comment_count\">[55]</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"display: flex; margin-top: 3px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"post_timestamp\">8시간 전</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"username\">한지민 fan</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 5층 끝 -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("footer {\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("\tleft: 0;\r\n");
      out.write("\tbottom: 0;\r\n");
      out.write("  \theight: 140px;\r\n");
      out.write("  \twidth: 100%;\r\n");
      out.write("  \tbackground-color: #5383E8;\r\n");
      out.write("  \tdisplay: flex;\r\n");
      out.write("  \talign-items: center;\r\n");
      out.write("  \tflex-direction: column;\r\n");
      out.write("  \tpadding-top : 20px;\r\n");
      out.write("  \tpadding-bottom: 80px;\r\n");
      out.write("}\r\n");
      out.write(".ft-ul {\r\n");
      out.write("\twidth: 970px;\r\n");
      out.write("\tmargin-right: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ft-nav {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ft-nav-item {\r\n");
      out.write("\tmargin-left: 20px;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tlist-style-type: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ft-nav-link {\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\talign-items: flex-start;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ft-text {\r\n");
      out.write("font-size: 8px;\r\n");
      out.write("color: white;\r\n");
      out.write("}\r\n");
      out.write(".ft-text-btn {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tjustify-content: space-between;\r\n");
      out.write("}\r\n");
      out.write(".ft-img {\r\n");
      out.write("width: 20px;\r\n");
      out.write("height: 20px;\r\n");
      out.write("margin-left: 10px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("\r\n");
      out.write("<div class=\"ft-ul\">\r\n");
      out.write("<ul class=\"ft-nav\">\r\n");
      out.write("    <li class=\"ft-nav-item\">\r\n");
      out.write("      <a class=\"ft-nav-link\" href=\"#\">About OP.GG</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"ft-nav-item\">\r\n");
      out.write("      <a class=\"ft-nav-link\" href=\"#\">로고 히스토리</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"ft-nav-item\">\r\n");
      out.write("      <a class=\"ft-nav-link\" href=\"#\">개인정보처리방침</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"ft-nav-item\">\r\n");
      out.write("      <a class=\"ft-nav-link\" href=\"#\">도움말</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"ft-nav-item\">\r\n");
      out.write("      <a class=\"ft-nav-link\" href=\"#\">제휴</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"ft-nav-item\">\r\n");
      out.write("      <a class=\"ft-nav-link\" href=\"#\">문의/피드백</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"ft-nav-item\">\r\n");
      out.write("      <a class=\"ft-nav-link\" href=\"#\">채용</a>\r\n");
      out.write("    </li>\r\n");
      out.write("  </ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"ft-text\">\r\n");
      out.write("<p>© 2012-2021 OP.GG. OP.GG isn’t endorsed by Riot Games and doesn’t reflect the views or opinions of Riot Games or anyone officially involved in producing or managing League of Legends. League of</p>\r\n");
      out.write("\r\n");
      out.write("<div class=\"ft-text-btn\">\r\n");
      out.write("<p>Legends and Riot Games are trademarks or registered trademarks of Riot Games, Inc. League of Legends © Riot Games, Inc.</p>\r\n");
      out.write("<div class=\"ft-btn\">\r\n");
      out.write("<img class=\"ft-img\" src=\"../assets/img/twitter.png\">\r\n");
      out.write("<img class=\"ft-img\" src=\"../assets/img/insta.png\">\r\n");
      out.write("<img class=\"ft-img\" src=\"../assets/img/facebook.png\">\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
